package Server;

public enum Command {
	MESSAGE, GET_DATABASE, DATABASE_LIST, TABLE_LIST,
	ADD_ENTRY, DELETE_ENTRY, EDIT_ENTRY,
	GET_TABLE, ADD_TABLE, DELETE_TABLE,
	ADD_COLUMN, DELETE_COLUMN, COLUMN_LIST,
	CONNECTION_SUCCESS, INCORRECT_USER, INCORRECT_PASSWORD, LOGIN
}