package Server;

public enum Command {
	MESSAGE, GET_TABLE_NAMES, DATABASE_LIST, DELETE_DATABASE, 
	TABLE_LIST, GET_ACTUAL_TABLE, ADD_TABLE, DELETE_TABLE,
	ADD_ENTRY, DELETE_ENTRY, EDIT_ENTRY,
	ADD_COLUMNS, DELETE_COLUMN,
	CONNECTION_SUCCESS, INCORRECT_USER, INCORRECT_PASSWORD, LOGIN
	
}